# NumPy Basics

NumPy is a Python library for working with numbers and arrays.

### Why use NumPy instead of lists?
Python lists can be slow for math. NumPy arrays store one data type and support **vectorization** — fast operations on a whole array, without loops.

## 1. Importing NumPy

Import NumPy with the short name `np`.

In [1]:
import numpy as np

## 2. Array Creation Techniques

You can create arrays from Python lists, or use helper functions for zeros, ones, constants, or ranges.

### 2.1 Converting Python Sequences

Use `np.array()` to make 1D and 2D arrays from Python lists.

In [2]:
# Make a 1D array from a list
simple_list = [10, 20, 30, 40, 50]
array_1d = np.array(simple_list)

# Make a 2D array from a list
nested_list = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(nested_list)

print("1D Array:", array_1d)
print("2D Array:\n", array_2d)

1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]]


### 2.2 Initializing Arrays with Placeholder Values

* `np.zeros()` — array of zeros
* `np.ones()` — array of ones
* `np.full()` — array filled with a chosen value
* `np.eye()` — identity matrix (ones on the diagonal, zeros elsewhere)

In [3]:
# Array of 3 zeros
zeros_array = np.zeros(3)

# 2x3 array of ones
ones_matrix = np.ones((2, 3))

# 2x2 array filled with 7
constant_matrix = np.full(shape=(2, 2), fill_value=7)

# 3x3 identity matrix
identity_matrix = np.eye(3)

print("Zeros Array:", zeros_array)
print("Ones Matrix:\n", ones_matrix)
print("Constant Matrix:\n", constant_matrix)
print("Identity Matrix:\n", identity_matrix)

Zeros Array: [0. 0. 0.]
Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]
Constant Matrix:
 [[7 7]
 [7 7]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2.3 Creating Sequence Ranges

* `np.arange()` — numbers from start to stop (step size), stop not included
* `np.linspace()` — a fixed number of evenly spaced values, start and stop included

In [20]:
# Numbers from 0 to 10, step 2
range_sequence = np.arange(0, 10, 2)

# 5 numbers evenly spaced between 0 and 10
linear_space = np.linspace(0, 10, 5)

print("arange sequence:", range_sequence)
print("linspace sequence:", linear_space)

arange sequence: [0 2 4 6 8]
linspace sequence: [ 0.   2.5  5.   7.5 10. ]


## 3. Array Attributes and Data Types

* `.shape` — size of each dimension
* `.ndim` — number of dimensions
* `.dtype` — data type of the elements

All elements in an array share the same `dtype`.

In [5]:
# Create an array with floating-point values
sample_array = np.array([[1.5, 2.3, 3.8], [4.0, 5.1, 6.2]])

print("Shape of the array:", sample_array.shape)
print("Number of dimensions:", sample_array.ndim)
print("Data type of elements:", sample_array.dtype)

Shape of the array: (2, 3)
Number of dimensions: 2
Data type of elements: float64


## 4. Indexing and Slicing Arrays

Indexing and slicing get specific elements or parts of an array.

### 4.1 Indexing and Slicing 1D Arrays

1D arrays use normal Python indexing: start at 0, and negative numbers count from the end.

In [6]:
arr = np.array([10, 20, 30, 40, 50])

print("First element (index 0):", arr[0])
print("Last element (index -1):", arr[-1])
print("Slicing from index 1 to 4 (exclusive):", arr[1:4])

First element (index 0): 10
Last element (index -1): 50
Slicing from index 1 to 4 (exclusive): [20 30 40]


### 4.2 Indexing and Slicing 2D Arrays

Use `array[row, column]` to get one element. Use `start:stop` on each dimension to slice a subgrid.

In [7]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Full Matrix:\n", matrix)
print("Element at row 1, column 2:", matrix[1, 2])

# Get a subgrid: rows from 1, columns from 1
subgrid = matrix[1:, 1:]
print("Extracted subgrid:\n", subgrid)

Full Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
Extracted subgrid:
 [[5 6]
 [8 9]]


## 5. Reshaping Arrays

`reshape` changes the shape of an array, not its values. The total number of elements must stay the same.

In [8]:
# Flat array with 25 elements
flat_values = np.arange(25)

# Reshape to 5x5
grid_5x5 = flat_values.reshape(5, 5)

print("Flat array:", flat_values)
print("Reshaped 5x5 grid:\n", grid_5x5)
print("Extracting middle 2x2 subgrid from the 5x5 matrix:\n", grid_5x5[1:3, 1:3])

Flat array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Reshaped 5x5 grid:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Extracting middle 2x2 subgrid from the 5x5 matrix:
 [[ 6  7]
 [11 12]]


## 6. Views vs. Copies in Memory

A slice is a **view**, not a copy. Changing a view also changes the original array. Use `.copy()` to make an independent array.

In [ ]:
# Make an array and a view
original_array = np.arange (6)
array_view = original_array [:3]
array_view[:] = 100
print("Original array after modifying the view:", original_array)

# Make a copy instead of a view
independent_copy = original_array[:3].copy()
independent_copy[:] = -1
print("Modified copy:", independent_copy)
print("Original array remains unaffected:", original_array)

Original array after modifying the view: [100 100 100   3   4   5]
Modified copy: [-1 -1 -1]
Original array remains unaffected: [100 100 100   3   4   5]


## 7. Vectorized Operations and Broadcasting

Vectorization runs math on whole arrays without loops. Broadcasting lets NumPy work with arrays of different, compatible shapes.

### 7.1 Basic Arithmetic and Element-wise Math

Operators like `+`, `/`, and `**` work element by element. Functions like `np.sqrt()` also work this way.

In [10]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

print("Element-wise addition:", a + b)
print("Element-wise division:", a / b)
print("Squaring b:", b ** 2)
print("Vectorized square roots:", np.sqrt([25, 9, 36]))

Element-wise addition: [ 3  7 11 15]
Element-wise division: [2.         1.33333333 1.2        1.14285714]
Squaring b: [ 1  9 25 49]
Vectorized square roots: [5. 3. 6.]


### 7.2 Matrix Multiplication vs. Element-wise Products

* `*` — element-wise multiplication
* `@` or `np.dot()` — matrix multiplication

In [22]:
left_matrix = np.array([[1, 2],
                       [3, 4]])
right_matrix = np.array([[1, 2],
                        [1, 2]])

print("Element-wise multiplication (*):\n", left_matrix * right_matrix)
print("Matrix multiplication (@):\n", left_matrix @ right_matrix)
print("Matrix multiplication (np.dot):\n", np.dot(left_matrix, right_matrix))

Element-wise multiplication (*):
 [[1 4]
 [3 8]]
Matrix multiplication (@):
 [[ 3  6]
 [ 7 14]]
Matrix multiplication (np.dot):
 [[ 3  6]
 [ 7 14]]


### 7.3 Array Broadcasting

Broadcasting stretches the smaller array's shape to match the larger one, so they can be used together in math.

In [12]:
base_arr = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Add 10 to every element
result_arr = base_arr + 10
print("Original Array:\n", base_arr)
print("After broadcasting +10:\n", result_arr)

Original Array:
 [[1 2 3]
 [4 5 6]]
After broadcasting +10:
 [[11 12 13]
 [14 15 16]]


## 8. Summary Statistics and Aggregations

NumPy has functions for statistics, like mean, sum, max, and min.

In [13]:
stats_data = np.array([1, 2, 3, 4, 5])

print("Arithmetic Mean:", np.mean(stats_data))
print("Sum of elements:", np.sum(stats_data))
print("Maximum value:", np.max(stats_data))
print("Minimum value:", np.min(stats_data))

Arithmetic Mean: 3.0
Sum of elements: 15
Maximum value: 5
Minimum value: 1


## 9. Boolean Filtering and Conditional Selection

Use a condition (boolean mask) to filter array elements. Use `np.where()` to replace values based on a condition.

In [ ]:
scores = np.array([10, 50, 75, 8])

# Get elements above 25
high_scores = scores[scores > 25]

# Label numbers as 'even' or 'odd'
parity_labels = np.where (scores % 2 == 0, "even", "odd")

print("Maximum score:", scores.max(), "at index:", scores.argmax())
print("Scores higher than 25:", high_scores)
print("Parity categorization:", parity_labels)

Maximum score: 75 at index: 2
Scores higher than 25: [50 75]
Parity categorization: ['even' 'even' 'odd' 'even']


## 10. Random Number Generation

Use `np.random.default_rng()` — the modern way to make random numbers. It's more reliable and reproducible than the old methods.

In [15]:
# Make a random generator with a fixed seed
rng = np.random.default_rng(seed=42)

# 2x2 array of random integers (0 to 10)
random_integers = rng.integers(0, 11, size=(2, 2))

# Old way to make random numbers
legacy_random_arr = np.random.randint(0, 10, size=(3, 3))

print("Modern Generator Random Integers:\n", random_integers)
print("Legacy Generator Random Integers:\n", legacy_random_arr)

Modern Generator Random Integers:
 [[0 8]
 [7 4]]
Legacy Generator Random Integers:
 [[1 0 1]
 [7 6 9]
 [2 5 7]]


## 11. Practical Applications: Linear Algebra Matrix Operations

NumPy has tools for linear algebra.

### 11.1 Standard Matrix Types

* **Square Matrix** — same number of rows and columns
* **Diagonal Matrix** — non-zero values only on the main diagonal
* **Identity Matrix** — diagonal matrix with ones
* **Triangular Matrix** — values only above (upper) or below (lower) the diagonal
* **Symmetric Matrix** — equal to its own transpose

In [16]:
# Square Matrix
square_mat = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Diagonal Matrix
diagonal_mat = np.diag([1, 2, 3])

# Identity Matrix of size 5
identity_mat = np.eye(5)

# Upper Triangular Matrix
upper_triangular = np.array([[1, 2, 3],
                             [0, 5, 6],
                             [0, 0, 9]])

# Lower Triangular Matrix
lower_triangular = np.array([[1, 0, 0],
                             [4, 5, 0],
                             [7, 8, 9]])

# Symmetric Matrix
symmetric_mat = np.array([[1, 2, 3],
                          [2, 5, 6],
                          [3, 6, 9]])

print("Square Matrix:\n", square_mat)
print("Diagonal Matrix:\n", diagonal_mat)
print("Identity Matrix:\n", identity_mat)
print("Upper Triangular Matrix:\n", upper_triangular)
print("Lower Triangular Matrix:\n", lower_triangular)
print("Symmetric Matrix:\n", symmetric_mat)

Square Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Upper Triangular Matrix:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]
Lower Triangular Matrix:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
Symmetric Matrix:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]


### 11.2 Transposing matrices

Transposing swaps rows and columns. Use `.T` or `np.transpose()`. For a non-square matrix, the shape also swaps.

In [17]:
matrix_2x3 = np.array([[1, 2, 3],
                       [4, 5, 6]])

transpose_matrix = np.transpose(matrix_2x3)

print("Original Matrix Shape:", matrix_2x3.shape)
print("Original Matrix:\n", matrix_2x3)
print("Transpose Matrix Shape:", transpose_matrix.shape)
print("Transpose Matrix:\n", transpose_matrix)

Original Matrix Shape: (2, 3)
Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transpose Matrix Shape: (3, 2)
Transpose Matrix:
 [[1 4]
 [2 5]
 [3 6]]


### 11.3 Advanced Linear Algebra Computations

`np.linalg` tools:
* **Trace** — sum of diagonal values, `np.trace()`
* **Determinant** — `np.linalg.det()`
* **Inverse** — `np.linalg.inv()`
* **Rank** — number of independent dimensions, `np.linalg.matrix_rank()`

In [18]:
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

invertible_matrix = np.array([[1, 2],
                              [3, 4]])

trace_value = np.trace(matrix_3x3)
det_value = np.linalg.det(invertible_matrix)
inverse_matrix = np.linalg.inv(invertible_matrix)
rank_value = np.linalg.matrix_rank(matrix_3x3)

print("Trace of 3x3 matrix:", trace_value)
print("Determinant of 2x2 matrix:", det_value)
print("Inverse of 2x2 matrix:\n", inverse_matrix)
print("Rank of 3x3 matrix:", rank_value)

Trace of 3x3 matrix: 15
Determinant of 2x2 matrix: -2.0000000000000004
Inverse of 2x2 matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Rank of 3x3 matrix: 2
