# NumPy fundamentals

NumPy provides fast, multidimensional arrays and vectorized operations. This notebook covers array creation, indexing, arithmetic, reshaping, and copying.

## Setup

The conventional alias for NumPy is `np`.

In [1]:
import numpy as np

rng = np.random.default_rng(seed=42)

## Creating arrays

Use `np.array` to convert Python sequences, or helper functions such as `zeros`, `ones`, and `arange` to create arrays directly.

In [2]:
numbers = np.array([1, 2, 3, 4, 5])
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("numbers:", numbers)
print("matrix shape:", matrix.shape)

numbers: [1 2 3 4 5]
matrix shape: (2, 3)


In [3]:
zeros = np.zeros(3)
ones = np.ones((2, 3))
constant = np.full((2, 2), 7)
identity = np.eye(3)

constant

array([[7, 7],
       [7, 7]])

## Ranges and random values

`arange` uses a stop value that is not included. `linspace` creates a chosen number of evenly spaced values, including both endpoints.

In [4]:
integers = np.arange(0, 10, 2)
points = np.linspace(0, 10, 5)
random_integers = rng.integers(0, 11, size=(2, 2))

print("arange:", integers)
print("linspace:", points)
print("random integers:\n", random_integers)

arange: [0 2 4 6 8]
linspace: [ 0.   2.5  5.   7.5 10. ]
random integers:
 [[0 8]
 [7 4]]


## Vectorized arithmetic

Array operations apply element by element without writing an explicit loop. Use `@` (or `np.matmul`) for matrix multiplication.

In [5]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

print("addition:", a + b)
print("division:", a / b)
print("squared b:", b ** 2)
print("square roots:", np.sqrt([25, 9, 36]))

addition: [ 3  7 11 15]
division: [2.         1.33333333 1.2        1.14285714]
squared b: [ 1  9 25 49]
square roots: [5. 3. 6.]


In [6]:
left = np.array([[1, 2], [3, 4]])
right = np.array([[1, 2], [1, 2]])

print("element-wise product:\n", left * right)
print("matrix product:\n", left @ right)
print("transpose:\n", left.T)

element-wise product:
 [[1 4]
 [3 8]]
matrix product:
 [[ 3  6]
 [ 7 14]]
transpose:
 [[1 3]
 [2 4]]


## Indexing, slicing, and reshaping

Indexes start at zero. Slices use `start:stop`, where `stop` is excluded. A reshape must preserve the total number of elements.

In [7]:
values = np.arange(25)
grid = values.reshape(5, 5)

print("second item:", values[1])
print("first three items:", values[:3])
print("middle 2 × 2 block:\n", grid[1:3, 1:3])

second item: 1
first three items: [0 1 2]
middle 2 × 2 block:
 [[ 6  7]
 [11 12]]


## Summary statistics and conditions

NumPy includes common reductions and boolean masks for filtering data.

In [8]:
scores = np.array([10, 50, 75, 8])
high_scores = scores[scores > 25]
labels = np.where(scores % 2 == 0, "even", "odd")

print("maximum:", scores.max(), "at index", scores.argmax())
print("high scores:", high_scores)
print("parity:", labels)

maximum: 75 at index 2
high scores: [50 75]
parity: ['even' 'even' 'odd' 'even']


## Views versus copies

A slice usually returns a **view**, so changing it can change the original array. Call `.copy()` when you need independent data.

In [9]:
original = np.arange(6)
view = original[:3]
view[:] = 100

independent = original[:3].copy()
independent[:] = -1

print("original after editing a view:", original)
print("independent copy:", independent)

original after editing a view: [100 100 100   3   4   5]
independent copy: [-1 -1 -1]


## Key takeaways

- Prefer vectorized array operations over Python loops when possible.
- Check `.shape` before reshaping or combining arrays.
- Use `.copy()` before editing a slice when the original must remain unchanged.